item_types = {
    "Dashboard": "Dashboard",
    "DataPipeline": "DataPipeline",
    "Datamart": "Datamart",
    "Environment": "Environment",
    "Eventhouse": "Eventhouse",
    "Eventstream": "Eventstream",
    "GraphQLApi": "GraphQL Api",
    "KQLDashboard": "KQL Dashboard",
    "KQLDatabase": "KQL Database",
    "KQLQueryset": "KQL Queryset",
    "Lakehouse": "Lakehouse",
    "MLExperiment": "ML Experiment",
    "MLModel": "ML Model",
    "MirroredDatabase": "Mirrored Database",
    "MirroredWarehouse": "Mirrored Warehouse",
    "MountedDataFactory": "Mounted Data Factory",
    "Notebook": "Notebook",
    "PaginatedReport": "Paginated Report",
    "Reflex": "Reflex",
    "Report": "Report",
    "SQLDatabase": "SQL Database",
    "SQLEndpoint": "SQL Endpoint",
    "SemanticModel": "Semantic Model",
    "SparkJobDefinition": "Spark Job Definition",
    "Warehouse": "Warehouse",
}