item_types = {
    "Dashboard": ["Dashboard", "dashboards"],
    "DataPipeline": ["Data Pipeline", "dataPipelines", "pipeline-content.json"],
    "Datamart": ["Datamart", "datamarts"],
    "Environment": ["Environment", "environments"],
    "Eventhouse": ["Eventhouse", "eventhouses", "EventhouseProperties.json"],
    "Eventstream": ["Eventstream", "eventstreams"],
    "GraphQLApi": ["GraphQL Api", "GraphQLApis"],
    "KQLDashboard": ["KQL Dashboard", "kqlDashboards"],
    "KQLDatabase": ["KQL Database", "kqlDatabases"],
    "KQLQueryset": ["KQL Queryset", "kqlQuerysets"],
    "Lakehouse": ["Lakehouse", "lakehouses"],
    "MLExperiment": ["ML Experiment", "mlExperiments"],
    "MLModel": ["ML Model", "mlModels"],
    "MirroredDatabase": ["Mirrored Database", "mirroredDatabases"],
    "MirroredWarehouse": ["Mirrored Warehouse", "mirroredWarehouses"],
    "MountedDataFactory": [
        "Mounted Data Factory",
        "mountedDataFactories",
        "mountedDataFactory-content.json",
    ],
    "Notebook": ["Notebook", "notebooks"],
    "PaginatedReport": ["Paginated Report", "paginatedReports"],
    "Reflex": ["Reflex", "reflexes"],
    "Report": ["Report", "reports", "report.json"],
    "SQLDatabase": ["SQL Database", "sqlDatabases"],
    "SQLEndpoint": ["SQL Endpoint", "sqlEndpoints"],
    "SemanticModel": ["Semantic Model", "semanticModels", "model.bim"],
    "SparkJobDefinition": ["Spark Job Definition", "sparkJobDefinitions"],
    "Warehouse": ["Warehouse", "warehouses"],
}
