item_types = {
    "Dashboard": ["Dashboard", "dashboards"],
    "DataPipeline": ["DataPipeline", "dataPipelines"],
    "Datamart": ["Datamart", "datamarts"],
    "Environment": ["Environment", "environments"],
    "Eventhouse": ["Eventhouse", "eventhouses"],
    "Eventstream": ["Eventstream", "eventstreams"],
    "GraphQLApi": ["GraphQL Api", "GraphQLApis"],
    "KQLDashboard": ["KQL Dashboard", "kqlDashboards"],
    "KQLDatabase": ["KQL Database", "kqlDatabases"],
    "KQLQueryset": ["KQL Queryset", "kqlQuerysets"],
    "Lakehouse": ["Lakehouse", "lakehouses"],
    "MLExperiment": ["ML Experiment", "mlExperiments"],
    "MLModel": ["ML Model", "mlModels"],
    "MirroredDatabase": ["Mirrored Database", "mirroredDatabases"],
    "MirroredWarehouse": ["Mirrored Warehouse", "mirroredWarehouses"],
    "MountedDataFactory": ["Mounted Data Factory", "mountedDataFactories"],
    "Notebook": ["Notebook", "notebooks"],
    "PaginatedReport": ["Paginated Report", "paginatedReports"],
    "Reflex": ["Reflex", "reflexes"],
    "Report": ["Report", "reports"],
    "SQLDatabase": ["SQL Database", "sqlDatabases"],
    "SQLEndpoint": ["SQL Endpoint", "sqlEndpoints"],
    "SemanticModel": ["Semantic Model", "semanticModels"],
    "SparkJobDefinition": ["Spark Job Definition", "sparkJobDefinitions"],
    "Warehouse": ["Warehouse", "warehouses"],
}
