"""Direct Lake Pre-warm Cache — creates a perspective, notebook, and daily schedule."""

import sempy.fabric as fabric
import sempy_labs._icons as icons
from sempy_labs._helper_functions import (
    resolve_workspace_name_and_id,
    resolve_dataset_name_and_id,
    _base_api,
    format_dax_object_name,
)
from typing import Optional
from uuid import UUID
import pandas as pd
from datetime import datetime, timedelta

_PERSPECTIVE_NAME = "_CacheWarmUp"
_PERSPECTIVE_DESC = (
    "Auto-generated by PBI Fixer for cache warming. "
    "Contains columns that were resident at {timestamp}. Do not delete."
)


def add_cache_warming(
    dataset: str | UUID,
    workspace: Optional[str | UUID] = None,
    scan_only: bool = False,
):
    """
    Direct Lake Pre-warm Cache.

    Scans the semantic model for Direct Lake tables, identifies currently
    resident columns, and (when not scan_only) creates a _CacheWarmUp
    perspective, a warm-up notebook, and a daily schedule.

    Parameters
    ----------
    dataset : str | uuid.UUID
        Name or ID of the semantic model.
    workspace : str | uuid.UUID, default=None
        The Fabric workspace name or ID.
    scan_only : bool, default=False
        If True, only prints the scan results without making changes.
    """

    (workspace_name, workspace_id) = resolve_workspace_name_and_id(workspace)
    (dataset_name, dataset_id) = resolve_dataset_name_and_id(dataset, workspace_id)

    # 1. Check if Direct Lake
    dfP = fabric.list_partitions(dataset=dataset_id, workspace=workspace_id)
    is_dl = any(r["Mode"] == "DirectLake" for _, r in dfP.iterrows())
    if not is_dl:
        print(
            f"{icons.red_dot} '{dataset_name}' is not a Direct Lake model. "
            f"This action is only for Direct Lake semantic models."
        )
        return

    # 2. Get resident columns
    dfC = fabric.list_columns(dataset=dataset_id, workspace=workspace_id, extended=True)
    dfC_resident = dfC[dfC["Is Resident"] == True].copy()

    if len(dfC_resident) == 0:
        print(
            f"{icons.yellow_dot} No columns are currently resident in '{dataset_name}'.\n"
            f"   Run this action during business hours when users have been active,\n"
            f"   so that the perspective captures the real working set."
        )
        return

    # 3. Build column list with temperature
    dfC_resident["DAX Object"] = format_dax_object_name(
        dfC_resident["Table Name"], dfC_resident["Column Name"]
    )
    total_cols = len(dfC_resident)
    total_tables = dfC_resident["Table Name"].nunique()

    # Also include relationship key columns as dependencies
    dfR = fabric.list_relationships(dataset=dataset_id, workspace=workspace_id)
    rel_cols = set()
    resident_tables = set(dfC_resident["Table Name"].unique())
    for _, r in dfR.iterrows():
        if r["From Table"] in resident_tables and r["To Table"] in resident_tables:
            rel_cols.add((r["From Table"], r["From Column"]))
            rel_cols.add((r["To Table"], r["To Column"]))

    # Add relationship columns not already resident
    existing = set(zip(dfC_resident["Table Name"], dfC_resident["Column Name"]))
    extra_rel = [(t, c) for t, c in rel_cols if (t, c) not in existing]
    extra_count = len(extra_rel)

    print(f"{icons.green_dot} '{dataset_name}' is Direct Lake — {total_cols} of {len(dfC)} columns currently resident across {total_tables} table(s).")
    if extra_count:
        print(f"   + {extra_count} relationship key column(s) added as dependencies.")
    print()
    print(f"   Columns for '{_PERSPECTIVE_NAME}' perspective:")
    print(f"   {'Table':<30} {'Column':<30} {'Temperature':>11}")
    print(f"   {'─' * 30} {'─' * 30} {'─' * 11}")

    temp_col = "Temperature" if "Temperature" in dfC_resident.columns else None
    for _, row in dfC_resident.sort_values(["Table Name", "Column Name"]).iterrows():
        temp = str(int(row[temp_col])) if temp_col and pd.notna(row.get(temp_col)) else "—"
        print(f"   {row['Table Name']:<30} {row['Column Name']:<30} {temp:>11}")
    for t, c in sorted(extra_rel):
        print(f"   {t:<30} {c:<30} {'(rel key)':>11}")

    print(f"\n   Total: {total_cols + extra_count} columns")

    if scan_only:
        print(f"\n{icons.info} Run in Fix mode to create perspective, notebook, and schedule.")
        return

    # 4. Create/update perspective via TOM
    from sempy_labs.tom import connect_semantic_model

    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    with connect_semantic_model(dataset=dataset_id, readonly=False, workspace=workspace_id) as tom:
        import Microsoft.AnalysisServices.Tabular as TOM

        # Check if perspective already exists
        persp_exists = any(p.Name == _PERSPECTIVE_NAME for p in tom.model.Perspectives)

        if persp_exists:
            # Remove old perspective, recreate fresh
            old = tom.model.Perspectives.Find(_PERSPECTIVE_NAME)
            if old is not None:
                tom.model.Perspectives.Remove(old)
            print(f"\n{icons.info} Existing '{_PERSPECTIVE_NAME}' perspective updated.")
        else:
            print(f"\n{icons.green_dot} Creating '{_PERSPECTIVE_NAME}' perspective...")

        # Create new perspective
        persp = TOM.Perspective()
        persp.Name = _PERSPECTIVE_NAME
        persp.Description = _PERSPECTIVE_DESC.format(timestamp=timestamp)
        tom.model.Perspectives.Add(persp)

        # Add all resident + relationship columns
        all_cols = existing.union(set(extra_rel))

        tables_added = {}  # table_name -> PerspectiveTable object
        for table_name, col_name in sorted(all_cols):
            # Ensure PerspectiveTable exists
            if table_name not in tables_added:
                try:
                    table_obj = tom.model.Tables.Find(table_name)
                    if table_obj is None:
                        continue
                except Exception:
                    continue
                pt = TOM.PerspectiveTable()
                pt.Table = table_obj
                persp.PerspectiveTables.Add(pt)
                tables_added[table_name] = pt

            # Add column
            try:
                pt_ref = tables_added[table_name]
                table_obj = tom.model.Tables.Find(table_name)
                col_obj = table_obj.Columns.Find(col_name) if table_obj else None
                if col_obj is None:
                    continue
                pc = TOM.PerspectiveColumn()
                pc.Column = col_obj
                pt_ref.PerspectiveColumns.Add(pc)
            except Exception:
                pass

    persp_action = "Updated" if persp_exists else "Created"
    print(f"{icons.green_dot} {persp_action} perspective '{_PERSPECTIVE_NAME}' with {len(all_cols)} columns.")

    # 5. Create warm-up notebook
    nb_name = f"_CacheWarmUp_{dataset_name.replace(' ', '_')}"
    nb_content = (
        f"# Fabric notebook source\n\n"
        f"# METADATA ********************\n\n"
        f"# META {{\n"
        f'# META   "kernel_info": {{\n'
        f'# META     "name": "synapse_pyspark"\n'
        f"# META   }}\n"
        f"# META }}\n\n"
        f"# CELL ********************\n\n"
        f"%pip install semantic-link-labs -q\n\n"
        f"# CELL ********************\n\n"
        f"# Cache Warm-Up: {dataset_name}\n"
        f"# Auto-generated by PBI Fixer. Warms the Direct Lake cache using the '_CacheWarmUp' perspective.\n\n"
        f"from sempy_labs.directlake import warm_direct_lake_cache_perspective\n\n"
        f'warm_direct_lake_cache_perspective(\n'
        f'    dataset="{dataset_name}",\n'
        f'    perspective="{_PERSPECTIVE_NAME}",\n'
        f'    add_dependencies=True,\n'
        f'    workspace="{workspace_name}",\n'
        f")\n"
    )

    # Check if notebook already exists
    try:
        items_resp = _base_api(
            request=f"/v1/workspaces/{workspace_id}/items?type=Notebook",
            method="get",
        )
        existing_nbs = items_resp.json().get("value", [])
        nb_exists = any(nb["displayName"] == nb_name for nb in existing_nbs)
        nb_id = next((nb["id"] for nb in existing_nbs if nb["displayName"] == nb_name), None)
    except Exception:
        nb_exists = False
        nb_id = None

    if not nb_exists:
        from sempy_labs._notebooks import create_notebook
        create_notebook(
            name=nb_name,
            notebook_content=nb_content,
            description=f"Direct Lake cache warm-up for '{dataset_name}'. Auto-generated by PBI Fixer.",
            workspace=workspace_id,
        )
        print(f"{icons.green_dot} Created notebook '{nb_name}'.")

        # Re-fetch to get notebook ID for scheduling
        try:
            items_resp = _base_api(
                request=f"/v1/workspaces/{workspace_id}/items?type=Notebook",
                method="get",
            )
            existing_nbs = items_resp.json().get("value", [])
            nb_id = next((nb["id"] for nb in existing_nbs if nb["displayName"] == nb_name), None)
        except Exception:
            nb_id = None
    else:
        print(f"{icons.info} Notebook '{nb_name}' already exists — skipping creation.")

    # 6. Schedule notebook daily at 07:00
    if nb_id is None:
        print(f"{icons.yellow_dot} Could not resolve notebook ID — schedule not created. Please schedule manually.")
        return

    # Detect the correct job type for notebooks
    _job_type = None
    try:
        jt_resp = _base_api(
            request=f"/v1/workspaces/{workspace_id}/items/{nb_id}/jobs",
            method="get",
        )
        job_types = jt_resp.json().get("value", [])
        if job_types:
            _job_type = job_types[0].get("jobType", None)
    except Exception:
        pass
    if not _job_type:
        _job_type = "RunNotebook"

    # Check for existing schedules
    schedule_exists = False
    try:
        sched_resp = _base_api(
            request=f"/v1/workspaces/{workspace_id}/items/{nb_id}/jobs/{_job_type}/schedules",
            method="get",
        )
        schedules = sched_resp.json().get("value", [])
        schedule_exists = len(schedules) > 0
    except Exception:
        pass

    if not schedule_exists:
        tomorrow = (datetime.utcnow() + timedelta(days=1)).strftime("%Y-%m-%dT00:00:00Z")
        far_future = "2099-12-31T23:59:59Z"
        schedule_payload = {
            "enabled": True,
            "configuration": {
                "type": "Daily",
                "startDateTime": tomorrow,
                "endDateTime": far_future,
                "localTimeZoneId": "W. Europe Standard Time",
                "times": ["07:00"],
            },
        }
        try:
            resp = _base_api(
                request=f"/v1/workspaces/{workspace_id}/items/{nb_id}/jobs/{_job_type}/schedules",
                method="post",
                payload=schedule_payload,
                status_codes=[201, 200],
            )
            print(f"{icons.green_dot} Scheduled '{nb_name}' daily at 07:00 (W. Europe Standard Time).")
        except Exception as e:
            err_detail = ""
            if hasattr(e, "response") and e.response is not None:
                try:
                    err_detail = e.response.json().get("message", e.response.text[:200])
                except Exception:
                    err_detail = str(e.response.status_code)
            print(f"{icons.yellow_dot} Could not create schedule: {e}")
            if err_detail:
                print(f"   Detail: {err_detail}")
            print(f"   Please schedule the notebook manually in the Fabric UI.")
    else:
        print(f"{icons.info} Schedule already exists for '{nb_name}' — skipping.")

    # Final summary
    print(f"\n{'─' * 60}")
    print(f"{icons.green_dot} Direct Lake cache warming setup complete:")
    print(f"   • Perspective '{_PERSPECTIVE_NAME}' — {len(all_cols)} columns")
    print(f"   • Notebook '{nb_name}' — in workspace '{workspace_name}'")
    print(f"   • Schedule — Daily at 07:00 (W. Europe Standard Time)")
    print(f"\n   To update the column list, run this action again during peak hours.")
