name: Semantic Link Labs

on: [push]

permissions:
  contents: write          # This is required for actions/checkout@v1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"

      - name: Setup dotnet
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: | 
            8.0.x

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache conda
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ steps.get-date.outputs.today }}-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          auto-update-conda: true
          activate-environment: fabric
          python-version: "3.10"
          environment-file: environment.yml
          channel-priority: strict

      - name: Install package
        shell: bash -el {0}
        run: |
          conda info
          pip install -e .

      # - name: Lint with flake8
      #   shell: bash -el {0}
      #   run: |
      #     flake8 sempy_labs tests --count --show-source --statistics
      #   continue-on-error: false

      # - name: Lint with mypy
      #   shell: bash -el {0}
      #   run: |
      #     mypy sempy_labs tests
      #   continue-on-error: false

      - name: Test with pytest
        shell: bash -el {0}
        run: |
          pytest -s tests/