name: Semantic Link Labs

on: [push]

permissions:
  contents: write          # This is required for actions/checkout@v1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: "3.10"

      - name: Setup dotnet
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: | 
            8.0.x

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache conda
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ steps.get-date.outputs.today }}-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167 # v3.3.0
        with:
          auto-update-conda: true
          activate-environment: fabric
          python-version: "3.10"
          environment-file: environment.yml
          channel-priority: strict

      - name: Install package
        shell: bash -el {0}
        run: |
          conda info
          pip install -e .

      # - name: Lint with flake8
      #   shell: bash -el {0}
      #   run: |
      #     flake8 sempy_labs tests --count --show-source --statistics
      #   continue-on-error: false

      # - name: Lint with mypy
      #   shell: bash -el {0}
      #   run: |
      #     mypy sempy_labs tests
      #   continue-on-error: false

      - name: Test with pytest
        shell: bash -el {0}
        run: |
          pytest -s tests/